on:
  push:
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set debug 
        id: set-debug-stage
        run: echo "BUILD_STAGE=debug" >> $GITHUB_OUTPUT
        
      - name: Get stage
        run: echo "The build stage is ${{ steps.set-debug-stage.outputs.BUILD_STAGE }}"
