name: CI
on:
  push:
    branches:
      - main
  workflows_dispatch:
  pull-request:
jobs:
  checkout:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, World!
      - name: Run a multi line script
        run: |
        echo Add other actions to build
        echo test, and deploy your project
      
