
name: file tree 1
 
on:
  workflow_dispatch:
jobs:
    
  file-tree:

    runs-on: self-hosted
    steps:
    - name: Install tree
      run: |
        brew update
        brew install tree
    - name: Execute tree
      run: time tree | tee filetreelist.txt
